### PR TITLE
auto-detect 64bit binaries on the commandline

### PR DESCRIPTION
**Pull request by BenGardiner**

### CODE REVIEW

**Comment by BenGardiner** [comment]
Thanks for taking the other 3 PRs. Is there an issue with this one?

**Comment by devttys0** [comment]
I've had a lot of issues using the `libmagic` library in `binwalk` (hence why `binwalk` no longer uses it!). Most notably, there are two Python  `magic` modules, one that comes with the actual `file` utility source, and another [here](https://github.com/ahupp/python-magic). Their module name is the same and they do the same thing, but their APIs are not compatible which is a source of much confusion. 

Although I don't think it would affect this application, I've also encountered minor revision changes to the `libmagic` library that break backwards compatibility, which causes a lot of issues as well. It is ugly, but I've found that it is actually more portable and reliable to just shell out to `file`!

Since this is a convenience feature, I would prefer that `idascript` not require the `magic` module. I think perhaps wrapping the `magic` code in `try-except` blocks and printing a warning telling the user that they either do not have the `magic` module installed, or that they have the wrong module installed, would be a fair compromise?

**Comment by BenGardiner** [comment]
That sounds like a great plan.

**Comment by BenGardiner** [comment]
Tested here on a python virtual environment:

```
⌁ [ben.gardiner:~/src/radare2-regressions/bins/mach0] [test-nomagic] master+* ± env TVHEADLESS=1 idascript test-arm64 ~/src/idame/just_analysis.py > /dev/null
libmagic module not found, automatic detection of 64bit binaries won't work
⌁ [ben.gardiner:~/src/radare2-regressions/bins/mach0] [test-nomagic] master+* ± pip2.7 install filemagic
Collecting filemagic
Installing collected packages: filemagic
Successfully installed filemagic-1.6
⌁ [ben.gardiner:~/src/radare2-regressions/bins/mach0] [test-nomagic] master+* ± env TVHEADLESS=1 idascript test-arm64 ~/src/idame/just_analysis.py > /dev/null
The 'import magic' module is not from the expected 'file-magic' package. Automatic detection of 64bit binaries won't work.
⌁ [ben.gardiner:~/src/radare2-regressions/bins/mach0] [test-nomagic] master+* ± yes | pip2.7 uninstall filemagic
Uninstalling filemagic-1.6:
[...]
Proceed (y/n)?   Successfully uninstalled filemagic-1.6
⌁ [ben.gardiner:~/src/radare2-regressions/bins/mach0] [test-nomagic] master+* ± pip2.7 install file-magic
Collecting file-magic
Installing collected packages: file-magic
Successfully installed file-magic-0.3.0
⌁ [ben.gardiner:~/src/radare2-regressions/bins/mach0] [test-nomagic] master+* ± env TVHEADLESS=1 idascript test-arm64 ~/src/idame/just_analysis.py > /dev/null
⌁ [ben.gardiner:~/src/radare2-regressions/bins/mach0] [test-nomagic] master+* ±
```

**Comment by devttys0** [comment]
Thanks!!

**Pull request merged**
